# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Upgrade pip and install packages
RUN pip install --upgrade pip
RUN pip install pandas tensorflow keras

# Default command
CMD ["python3"]